CREATE DATABASE build_a_smoothie;

\c build_a_smoothie;

DROP TABLE IF EXISTS smoothies;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE smoothies (
  ID SERIAL NOT NULL PRIMARY KEY,
  USER_ID INTEGER NOT NULL REFERENCES users,
  TITLE VARCHAR(255) NOT NULL,
  INGREDIENTS JSONB NOT NULL,
  INSTRUCTIONS TEXT
);
